name: kavana_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  d_session: ^0.0.3
  fd_log: ^0.0.7
  http: ^1.2.2
  intl: ^0.19.0
  get: ^4.6.6
  gap: ^3.0.1
  google_fonts: ^6.2.1
  d_info: ^0.2.0
  d_chart: ^2.8.0
  calendar_view: ^1.2.0
  google_generative_ai: ^0.4.5
  flutter_markdown: ^0.7.3+1
  image_picker: ^1.1.2
  geolocator: ^12.0.0 
  url_launcher: ^6.3.1 
  geocoding: ^3.0.0 
  google_maps_flutter: ^2.5.0
  flutter_timezone: ^5.0.1
  permission_handler: ^11.1.0
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.3
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env